user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
AjouterCours:
    path:     /AjouterCours
    defaults: { _controller: CoursBundle:Cours:AjouterCours }

AfficherCours:
    path:     /AfficherCours
    defaults: { _controller: CoursBundle:Cours:AfficherCours }

ModifierCours:
    path:     /ModifierCours/{id}
    defaults: { _controller: CoursBundle:Cours:ModifierCours }

SupprimerCours:
    path:     /SupprimerCours/{id}
    defaults: { _controller: CoursBundle:Cours:SupprimerCours }
AdminCours:
    path:     /index
    defaults: { _controller: UserBundle:Default:AdminCours }
